case country
        
        when "afghanistan" then   "afg"
        when "af" then   "afg"
        when "afg" then   "afg"
        when "\u00c5land islands" then   "ala"
        when "ax" then   "ala"
        when "ala" then   "ala"
        when "albania" then   "alb"
        when "al" then   "alb"
        when "alb" then   "alb"
        when "netherlands antilles" then   "ant"
        when "curacao" then   "ant"
        when "ant" then   "ant"
        when "algeria" then   "dza"
        when "dz" then   "dza"
        when "dza" then   "dza"
        when "american samoa" then   "asm"
        when "as" then   "asm"
        when "asm" then   "asm"
        when "samoa then   american" then   "asm"
        when "andorra" then   "and"
        when "ad" then   "and"
        when "and" then   "and"
        when "angola" then   "ago"
        when "ao" then   "ago"
        when "ago" then   "ago"
        when "anguilla" then   "aia"
        when "ai" then   "aia"
        when "aia" then   "aia"
        when "antarctica" then   "ata"
        when "aq" then   "ata"
        when "ata" then   "ata"
        when "antigua and barbuda" then   "atg"
        when "ag" then   "atg"
        when "atg" then   "atg"
        when "antigua  barbuda" then   "atg"
        when "antiguabarbuda" then   "atg"
        when "antigua & barbuda" then   "atg"
        when "antigua/barbuda" then   "atg"
        when "argentina" then   "arg"
        when "ar" then   "arg"
        when "arg" then   "arg"
        when "armenia" then   "arm"
        when "am" then   "arm"
        when "arm" then   "arm"
        when "aruba" then   "abw"
        when "aw" then   "abw"
        when "abw" then   "abw"
        when "australia" then   "aus"
        when "au" then   "aus"
        when "aus" then   "aus"
        when "austria" then   "aut"
        when "at" then   "aut"
        when "aut" then   "aut"
        when "azerbaijan" then   "aze"
        when "az" then   "aze"
        when "aze" then   "aze"
        when "bahamas" then   "bhs"
        when "bs" then   "bhs"
        when "bhs" then   "bhs"
        when "bahrain" then   "bhr"
        when "bh" then   "bhr"
        when "bhr" then   "bhr"
        when "bangladesh" then   "bgd"
        when "bd" then   "bgd"
        when "bgd" then   "bgd"
        when "barbados" then   "brb"
        when "bb" then   "brb"
        when "brb" then   "brb"
        when "belarus" then   "blr"
        when "by" then   "blr"
        when "blr" then   "blr"
        when "belgium" then   "bel"
        when "be" then   "bel"
        when "bel" then   "bel"
        when "belize" then   "blz"
        when "bz" then   "blz"
        when "blz" then   "blz"
        when "benin" then   "ben"
        when "bj" then   "ben"
        when "ben" then   "ben"
        when "bermuda" then   "bmu"
        when "bm" then   "bmu"
        when "bmu" then   "bmu"
        when "bhutan" then   "btn"
        when "bt" then   "btn"
        when "btn" then   "btn"
        when "bolivia plurinational state of" then   "bol"
        when "bo" then   "bol"
        when "bol" then   "bol"
        when "bolivia" then   "bol"
        when "bonaire sint eustatius and saba" then   "bes"
        when "bonaire then   sint eustatius and saba" then   "bes"
        when "bq" then   "bes"
        when "bes" then   "bes"
        when "bonaire st eustatius and saba" then   "bes"
        when "virgin islands" then   "bes"
        when "bonaire saint eustatius and saba" then   "bes"
        when "bonaire" then   "bes"
        when "bosnia and herzegovina" then   "bih"
        when "ba" then   "bih"
        when "bih" then   "bih"
        when "bosnia and herzegovnia" then   "bih"
        when "bosnia herzegovina" then   "bih"
        when "bosnia and herzegowina" then   "bih"
        when "botswana" then   "bwa"
        when "bw" then   "bwa"
        when "bwa" then   "bwa"
        when "bouvet island" then   "bvt"
        when "bv" then   "bvt"
        when "bvt" then   "bvt"
        when "brazil" then   "bra"
        when "br" then   "bra"
        when "bra" then   "bra"
        when "british indian ocean territory" then   "iot"
        when "io" then   "iot"
        when "iot" then   "iot"
        when "brunei darussalam" then   "brn"
        when "bn" then   "brn"
        when "brn" then   "brn"
        when "brunei" then   "brn"
        when "bulgaria" then   "bgr"
        when "bg" then   "bgr"
        when "bgr" then   "bgr"
        when "burkina faso" then   "bfa"
        when "bf" then   "bfa"
        when "bfa" then   "bfa"
        when "burundi" then   "bdi"
        when "bi" then   "bdi"
        when "bdi" then   "bdi"
        when "cambodia" then   "khm"
        when "kh" then   "khm"
        when "khm" then   "khm"
        when "cameroon" then   "cmr"
        when "cm" then   "cmr"
        when "cmr" then   "cmr"
        when "cameroon united republic of" then   "cmr"
        when "canada" then   "can"
        when "ca" then   "can"
        when "can" then   "can"
        when "cabo verde" then   "cpv"
        when "cv" then   "cpv"
        when "cpv" then   "cpv"
        when "cape verde" then   "cpv"
        when "cape verde republic of" then   "cpv"
        when "cape verde then   republic of" then   "cpv"
        when "cayman islands" then   "cym"
        when "ky" then   "cym"
        when "cym" then   "cym"
        when "central african republic" then   "caf"
        when "cf" then   "caf"
        when "caf" then   "caf"
        when "chad" then   "tcd"
        when "td" then   "tcd"
        when "tcd" then   "tcd"
        when "chile" then   "chl"
        when "cl" then   "chl"
        when "chl" then   "chl"
        when "china" then   "chn"
        when "cn" then   "chn"
        when "chn" then   "chn"
        when "christmas island" then   "cxr"
        when "cx" then   "cxr"
        when "cxr" then   "cxr"
        when "cocos (keeling) islands" then   "cck"
        when "cc" then   "cck"
        when "cck" then   "cck"
        when "cocos (k) i" then   "cck"
        when "cocos (k) i." then   "cck"
        when "colombia" then   "col"
        when "co" then   "col"
        when "col" then   "col"
        when "comoros" then   "com"
        when "km" then   "com"
        when "com" then   "com"
        when "congo" then   "cog"
        when "cg" then   "cog"
        when "cog" then   "cog"
        when "republic of the congo" then   "cog"
        when "congo the democratic republic of the" then   "cod"
        when "congo dem rep of" then   "cod"
        when "congo then   dem. rep. of" then   "cod"
        when "cd" then   "cod"
        when "cod" then   "cod"
        when "congo democratic republic of" then   "cod"
        when "democratic republic of the congo" then   "cod"
        when "congo demrepof" then   "cod"
        when "cook islands" then   "cok"
        when "ck" then   "cok"
        when "cok" then   "cok"
        when "costa rica" then   "cri"
        when "cr" then   "cri"
        when "cri" then   "cri"
        when "c\u00f4te divoire" then   "civ"
        when "cote divoire" then   "civ"
        when "cote d'ivoire" then   "civ"
        when "ci" then   "civ"
        when "civ" then   "civ"
        when "ivory coast" then   "civ"
        when "croatia" then   "hrv"
        when "hr" then   "hrv"
        when "hrv" then   "hrv"
        when "cuba" then   "cub"
        when "cu" then   "cub"
        when "cub" then   "cub"
        when "cura\u00e7ao" then   "cuw"
        when "cw" then   "cuw"
        when "cuw" then   "cuw"
        when "cyprus" then   "cyp"
        when "cy" then   "cyp"
        when "cyp" then   "cyp"
        when "czech republic" then   "cze"
        when "cz" then   "cze"
        when "cze" then   "cze"
        when "denmark" then   "dnk"
        when "dk" then   "dnk"
        when "dnk" then   "dnk"
        when "djibouti" then   "dji"
        when "dj" then   "dji"
        when "dji" then   "dji"
        when "dominica" then   "dma"
        when "dm" then   "dma"
        when "dma" then   "dma"
        when "dominican republic" then   "dom"
        when "do" then   "dom"
        when "dom" then   "dom"
        when "ecuador" then   "ecu"
        when "ec" then   "ecu"
        when "ecu" then   "ecu"
        when "egypt" then   "egy"
        when "eg" then   "egy"
        when "egy" then   "egy"
        when "el salvador" then   "slv"
        when "sv" then   "slv"
        when "slv" then   "slv"
        when "equatorial guinea" then   "gnq"
        when "gq" then   "gnq"
        when "gnq" then   "gnq"
        when "eritrea" then   "eri"
        when "er" then   "eri"
        when "eri" then   "eri"
        when "estonia" then   "est"
        when "ee" then   "est"
        when "est" then   "est"
        when "ethiopia" then   "eth"
        when "et" then   "eth"
        when "eth" then   "eth"
        when "falkland islands (malvinas)" then   "flk"
        when "fk" then   "flk"
        when "flk" then   "flk"
        when "faroe islands" then   "fro"
        when "fo" then   "fro"
        when "fro" then   "fro"
        when "fiji" then   "fji"
        when "fj" then   "fji"
        when "fji" then   "fji"
        when "fiji islands" then   "fji"
        when "finland" then   "fin"
        when "fi" then   "fin"
        when "fin" then   "fin"
        when "france" then   "fra"
        when "fr" then   "fra"
        when "fra" then   "fra"
        when "french guiana" then   "guf"
        when "gf" then   "guf"
        when "guf" then   "guf"
        when "french polynesia" then   "pyf"
        when "pf" then   "pyf"
        when "pyf" then   "pyf"
        when "french southern territories" then   "atf"
        when "tf" then   "atf"
        when "atf" then   "atf"
        when "gabon" then   "gab"
        when "ga" then   "gab"
        when "gab" then   "gab"
        when "gambia" then   "gmb"
        when "gm" then   "gmb"
        when "gmb" then   "gmb"
        when "the gambia" then   "gmb"
        when "georgia" then   "geo"
        when "ge" then   "geo"
        when "geo" then   "geo"
        when "abkhazia georgia" then   "geo"
        when "abkhazia then   georgia" then   "geo"
        when "germany" then   "deu"
        when "de" then   "deu"
        when "deu" then   "deu"
        when "ghana" then   "gha"
        when "gh" then   "gha"
        when "gha" then   "gha"
        when "gibraltar" then   "gib"
        when "gi" then   "gib"
        when "gib" then   "gib"
        when "greece" then   "grc"
        when "gr" then   "grc"
        when "grc" then   "grc"
        when "greenland" then   "grl"
        when "gl" then   "grl"
        when "grl" then   "grl"
        when "grenada" then   "grd"
        when "gd" then   "grd"
        when "grd" then   "grd"
        when "guadeloupe" then   "glp"
        when "gp" then   "glp"
        when "glp" then   "glp"
        when "guam" then   "gum"
        when "gu" then   "gum"
        when "gum" then   "gum"
        when "guatemala" then   "gtm"
        when "gt" then   "gtm"
        when "gtm" then   "gtm"
        when "guernsey" then   "ggy"
        when "gg" then   "ggy"
        when "ggy" then   "ggy"
        when "guinea" then   "gin"
        when "gn" then   "gin"
        when "gin" then   "gin"
        when "guinea-bissau" then   "gnb"
        when "gw" then   "gnb"
        when "gnb" then   "gnb"
        when "guinea bissau" then   "gnb"
        when "guyana" then   "guy"
        when "gy" then   "guy"
        when "guy" then   "guy"
        when "haiti" then   "hti"
        when "ht" then   "hti"
        when "hti" then   "hti"
        when "heard island and mcdonald islands" then   "hmd"
        when "hm" then   "hmd"
        when "hmd" then   "hmd"
        when "holy see (vatican city state)" then   "vat"
        when "va" then   "vat"
        when "vat" then   "vat"
        when "vatican city" then   "vat"
        when "honduras" then   "hnd"
        when "hn" then   "hnd"
        when "hnd" then   "hnd"
        when "hong kong" then   "hkg"
        when "hk" then   "hkg"
        when "hkg" then   "hkg"
        when "hungary" then   "hun"
        when "hu" then   "hun"
        when "hun" then   "hun"
        when "iceland" then   "isl"
        when "is" then   "isl"
        when "isl" then   "isl"
        when "india" then   "ind"
        when "in" then   "ind"
        when "ind" then   "ind"
        when "indonesia" then   "idn"
        when "id" then   "idn"
        when "idn" then   "idn"
        when "iran islamic republic of" then   "irn"
        when "ir" then   "irn"
        when "irn" then   "irn"
        when "iran" then   "irn"
        when "iraq" then   "irq"
        when "iq" then   "irq"
        when "irq" then   "irq"
        when "ireland" then   "irl"
        when "ie" then   "irl"
        when "irl" then   "irl"
        when "ireland republic of" then   "irl"
        when "ireland then   republic of" then   "irl"
        when "isle of man" then   "imn"
        when "im" then   "imn"
        when "imn" then   "imn"
        when "israel" then   "isr"
        when "il" then   "isr"
        when "isr" then   "isr"
        when "italy" then   "ita"
        when "it" then   "ita"
        when "ita" then   "ita"
        when "jamaica" then   "jam"
        when "jm" then   "jam"
        when "jam" then   "jam"
        when "japan" then   "jpn"
        when "jp" then   "jpn"
        when "jpn" then   "jpn"
        when "jersey" then   "jey"
        when "je" then   "jey"
        when "jey" then   "jey"
        when "jordan" then   "jor"
        when "jo" then   "jor"
        when "jor" then   "jor"
        when "kazakhstan" then   "kaz"
        when "kz" then   "kaz"
        when "kaz" then   "kaz"
        when "kazakstan" then   "kaz"
        when "kenya" then   "ken"
        when "ke" then   "ken"
        when "ken" then   "ken"
        when "kiribati" then   "kir"
        when "ki" then   "kir"
        when "kir" then   "kir"
        when "korea democratic peoples republic of" then   "prk"
        when "kp" then   "prk"
        when "prk" then   "prk"
        when "korea republic of" then   "kor"
        when "korea then   republic of" then   "kor"
        when "kr" then   "kor"
        when "kor" then   "kor"
        when "south korea" then   "kor"
        when "korea" then   "kor"
        when "korea rep of" then   "kor"
        when "korea then   rep. of" then   "kor"
        when "korea dem peoples rep of" then   "kor"
        when "korea then   dem. people's rep. of" then   "kor"
        when "kuwait" then   "kwt"
        when "kw" then   "kwt"
        when "kwt" then   "kwt"
        when "kyrgyzstan" then   "kgz"
        when "kg" then   "kgz"
        when "kgz" then   "kgz"
        when "lao people's democratic republic" then   "lao"
        when "la" then   "lao"
        when "lao" then   "lao"
        when "laos" then   "lao"
        when "lao peoples demo rep" then   "lao"
        when "lao peoples dem rep" then   "lao"
        when "lao then   people's dem. rep." then   "lao"
        when "lao people's demo. rep." then   "lao"
        when "latvia" then   "lva"
        when "lv" then   "lva"
        when "lva" then   "lva"
        when "lebanon" then   "lbn"
        when "lb" then   "lbn"
        when "lbn" then   "lbn"
        when "lesotho" then   "lso"
        when "ls" then   "lso"
        when "lso" then   "lso"
        when "liberia" then   "lbr"
        when "lr" then   "lbr"
        when "lbr" then   "lbr"
        when "libya" then   "lby"
        when "ly" then   "lby"
        when "lby" then   "lby"
        when "libyan arab jamahiriya" then   "lby"
        when "liechtenstein" then   "lie"
        when "li" then   "lie"
        when "lie" then   "lie"
        when "lithuania" then   "ltu"
        when "lt" then   "ltu"
        when "ltu" then   "ltu"
        when "luxembourg" then   "lux"
        when "lu" then   "lux"
        when "lux" then   "lux"
        when "macao" then   "mac"
        when "mo" then   "mac"
        when "mac" then   "mac"
        when "macau" then   "mac"
        when "macedonia the former yugoslav republic of" then   "mkd"
        when "mk" then   "mkd"
        when "mkd" then   "mkd"
        when "macedonia" then   "mkd"
        when "fyro macedonia" then   "mkd"
        when "f.y.r.o. macedonia" then   "mkd"
        when "madagascar" then   "mdg"
        when "mg" then   "mdg"
        when "mdg" then   "mdg"
        when "madagascar malagasy" then   "mdg"
        when "madagascar (malagasy)" then   "mdg"
        when "malawi" then   "mwi"
        when "mw" then   "mwi"
        when "mwi" then   "mwi"
        when "malaysia" then   "mys"
        when "my" then   "mys"
        when "mys" then   "mys"
        when "maldives" then   "mdv"
        when "mv" then   "mdv"
        when "mdv" then   "mdv"
        when "mali" then   "mli"
        when "ml" then   "mli"
        when "mli" then   "mli"
        when "malta" then   "mlt"
        when "mt" then   "mlt"
        when "mlt" then   "mlt"
        when "marshall islands" then   "mhl"
        when "mh" then   "mhl"
        when "mhl" then   "mhl"
        when "martinique" then   "mtq"
        when "mq" then   "mtq"
        when "mtq" then   "mtq"
        when "mauritania" then   "mrt"
        when "mr" then   "mrt"
        when "mrt" then   "mrt"
        when "mauritius" then   "mus"
        when "mu" then   "mus"
        when "mus" then   "mus"
        when "mayotte" then   "myt"
        when "yt" then   "myt"
        when "myt" then   "myt"
        when "mexico" then   "mex"
        when "mx" then   "mex"
        when "mex" then   "mex"
        when "micronesia federated states of" then   "fsm"
        when "fm" then   "fsm"
        when "fsm" then   "fsm"
        when "micronesia" then   "fsm"
        when "federated states of micronesia" then   "fsm"
        when "micronesia fed states of" then   "fsm"
        when "micronesia then   fed. states of" then   "fsm"
        when "moldova republic of" then   "mda"
        when "moldova then   republic of" then   "mda"
        when "md" then   "mda"
        when "mda" then   "mda"
        when "moldova" then   "mda"
        when "monaco" then   "mco"
        when "mc" then   "mco"
        when "mco" then   "mco"
        when "mongolia" then   "mng"
        when "mn" then   "mng"
        when "mng" then   "mng"
        when "montenegro" then   "mne"
        when "me" then   "mne"
        when "mne" then   "mne"
        when "montserrat" then   "msr"
        when "ms" then   "msr"
        when "msr" then   "msr"
        when "morocco" then   "mar"
        when "ma" then   "mar"
        when "mar" then   "mar"
        when "mozambique" then   "moz"
        when "mz" then   "moz"
        when "moz" then   "moz"
        when "myanmar" then   "mmr"
        when "mm" then   "mmr"
        when "mmr" then   "mmr"
        when "namibia" then   "nam"
        when "na" then   "nam"
        when "nam" then   "nam"
        when "nauru" then   "nru"
        when "nr" then   "nru"
        when "nru" then   "nru"
        when "nepal" then   "npl"
        when "np" then   "npl"
        when "npl" then   "npl"
        when "netherlands" then   "nld"
        when "nl" then   "nld"
        when "nld" then   "nld"
        when "the netherlands" then   "nld"
        when "new caledonia" then   "ncl"
        when "nc" then   "ncl"
        when "ncl" then   "ncl"
        when "new zealand" then   "nzl"
        when "nz" then   "nzl"
        when "nzl" then   "nzl"
        when "nicaragua" then   "nic"
        when "ni" then   "nic"
        when "nic" then   "nic"
        when "niger" then   "ner"
        when "ne" then   "ner"
        when "ner" then   "ner"
        when "nigeria" then   "nga"
        when "ng" then   "nga"
        when "nga" then   "nga"
        when "niue" then   "niu"
        when "nu" then   "niu"
        when "niu" then   "niu"
        when "norfolk island" then   "nfk"
        when "nf" then   "nfk"
        when "nfk" then   "nfk"
        when "northern mariana islands" then   "mnp"
        when "mp" then   "mnp"
        when "mnp" then   "mnp"
        when "marianna islands" then   "mnp"
        when "norway" then   "nor"
        when "no" then   "nor"
        when "nor" then   "nor"
        when "oman" then   "omn"
        when "om" then   "omn"
        when "omn" then   "omn"
        when "oman sultanate of" then   "omn"
        when "pakistan" then   "pak"
        when "pk" then   "pak"
        when "pak" then   "pak"
        when "palau" then   "plw"
        when "pw" then   "plw"
        when "plw" then   "plw"
        when "palestine state of" then   "pse"
        when "ps" then   "pse"
        when "pse" then   "pse"
        when "palestinian territory" then   "pse"
        when "state of palestine" then   "pse"
        when "palestinian territories" then   "pse"
        when "panama" then   "pan"
        when "pa" then   "pan"
        when "pan" then   "pan"
        when "papua new guinea" then   "png"
        when "pg" then   "png"
        when "png" then   "png"
        when "paraguay" then   "pry"
        when "py" then   "pry"
        when "pry" then   "pry"
        when "peru" then   "per"
        when "pe" then   "per"
        when "per" then   "per"
        when "philippines" then   "phl"
        when "ph" then   "phl"
        when "phl" then   "phl"
        when "pitcairn" then   "pcn"
        when "pn" then   "pcn"
        when "pcn" then   "pcn"
        when "poland" then   "pol"
        when "pl" then   "pol"
        when "pol" then   "pol"
        when "portugal" then   "prt"
        when "pt" then   "prt"
        when "prt" then   "prt"
        when "puerto rico" then   "pri"
        when "pr" then   "pri"
        when "pri" then   "pri"
        when "qatar" then   "qat"
        when "qa" then   "qat"
        when "qat" then   "qat"
        when "r\u00e9union" then   "reu"
        when "reunion" then   "reu"
        when "re" then   "reu"
        when "reu" then   "reu"
        when "romania" then   "rou"
        when "ro" then   "rou"
        when "rou" then   "rou"
        when "russian federation" then   "rus"
        when "ru" then   "rus"
        when "rus" then   "rus"
        when "russia" then   "rus"
        when "rwanda" then   "rwa"
        when "rw" then   "rwa"
        when "rwa" then   "rwa"
        when "saint barth\u00e9lemy" then   "blm"
        when "bl" then   "blm"
        when "blm" then   "blm"
        when "st barthelemy" then   "blm"
        when "saint barthelemy" then   "blm"
        when "saint helena ascension and tristan da cunha" then   "shn"
        when "sh" then   "shn"
        when "shn" then   "shn"
        when "saint kitts and nevis" then   "kna"
        when "kn" then   "kna"
        when "kna" then   "kna"
        when "st kitts and nevis" then   "kna"
        when "st kitts  nevis" then   "kna"
        when "st. kitts - nevis" then   "kna"
        when "st. kitts and nevis" then   "kna"
        when "saint lucia" then   "lca"
        when "lc" then   "lca"
        when "lca" then   "lca"
        when "st lucia" then   "lca"
        when "st. lucia" then   "lca"
        when "saint martin (french part)" then   "maf"
        when "mf" then   "maf"
        when "maf" then   "maf"
        when "saint martin" then   "maf"
        when "st martin" then   "maf"
        when "st martin" then   "maf"
        when "st. martin" then   "maf"
        when "saint pierre and miquelon" then   "spm"
        when "st. pierre and miquelon" then   "spm"
        when "pm" then   "spm"
        when "spm" then   "spm"
        when "st pierre and miquelon" then   "spm"
        when "saint vincent and the grenadines" then   "vct"
        when "vc" then   "vct"
        when "vct" then   "vct"
        when "saint vincent & grenadines" then   "vct"
        when "st vincent and the grenadines" then   "vct"
        when "saint vincent and the grenadin" then   "vct"
        when "st vincentgrenadines" then   "vct"
        when "st. vincent/grenadines" then   "vct"
        when "samoa" then   "wsm"
        when "ws" then   "wsm"
        when "wsm" then   "wsm"
        when "samoa independent state of" then   "wsm"
        when "samoa then   independent state of" then   "wsm"
        when "san marino" then   "smr"
        when "sm" then   "smr"
        when "smr" then   "smr"
        when "sao tome and principe" then   "stp"
        when "sao tome & principe" then   "stp"
        when "s\u00e3o tom\u00e9 and pr\u00edncipe" then   "stp"
        when "st" then   "stp"
        when "stp" then   "stp"
        when "sao tome  principe" then   "stp"
        when "saudi arabia" then   "sau"
        when "sa" then   "sau"
        when "sau" then   "sau"
        when "senegal" then   "sen"
        when "sn" then   "sen"
        when "sen" then   "sen"
        when "serbia" then   "srb"
        when "belgrade" then   "srb"
        when "rs" then   "srb"
        when "srb" then   "srb"
        when "seychelles" then   "syc"
        when "sc" then   "syc"
        when "syc" then   "syc"
        when "seychelles islands" then   "syc"
        when "sierra leone" then   "sle"
        when "sl" then   "sle"
        when "sle" then   "sle"
        when "singapore" then   "sgp"
        when "sg" then   "sgp"
        when "sgp" then   "sgp"
        when "sint maarten (dutch part)" then   "sxm"
        when "sx" then   "sxm"
        when "sxm" then   "sxm"
        when "sint maarten" then   "sxm"
        when "st maarten" then   "sxm"
        when "country of sint maarten" then   "sxm"
        when "slovakia" then   "svk"
        when "sk" then   "svk"
        when "svk" then   "svk"
        when "slovakia slovak republic" then   "svk"
        when "slovakia (slovak republic)" then   "svk"
        when "slovenia" then   "svn"
        when "si" then   "svn"
        when "svn" then   "svn"
        when "solomon islands" then   "slb"
        when "sb" then   "slb"
        when "slb" then   "slb"
        when "somalia" then   "som"
        when "so" then   "som"
        when "som" then   "som"
        when "south africa" then   "zaf"
        when "za" then   "zaf"
        when "zaf" then   "zaf"
        when "south georgia and the south sandwich islands" then   "sgs"
        when "gs" then   "sgs"
        when "sgs" then   "sgs"
        when "south sudan" then   "ssd"
        when "ss" then   "ssd"
        when "ssd" then   "ssd"
        when "spain" then   "esp"
        when "es" then   "esp"
        when "esp" then   "esp"
        when "sri lanka" then   "lka"
        when "lk" then   "lka"
        when "lka" then   "lka"
        when "sudan" then   "sdn"
        when "sd" then   "sdn"
        when "sdn" then   "sdn"
        when "suriname" then   "sur"
        when "sr" then   "sur"
        when "sur" then   "sur"
        when "svalbard and jan mayen" then   "sjm"
        when "sj" then   "sjm"
        when "sjm" then   "sjm"
        when "svalbard" then   "sjm"
        when "svalbardjan mayen isl" then   "sjm"
        when "svalbard/jan mayen isl." then   "sjm"
        when "swaziland" then   "swz"
        when "sz" then   "swz"
        when "swz" then   "swz"
        when "sweden" then   "swe"
        when "se" then   "swe"
        when "swe" then   "swe"
        when "switzerland" then   "che"
        when "ch" then   "che"
        when "che" then   "che"
        when "syrian arab republic" then   "syr"
        when "sy" then   "syr"
        when "syr" then   "syr"
        when "syria" then   "syr"
        when "syrian arab rep" then   "syr"
        when "taiwan province of china" then   "twn"
        when "tw" then   "twn"
        when "twn" then   "twn"
        when "taiwan" then   "twn"
        when "taiwan republic of china" then   "twn"
        when "taiwan then   province of china" then   "twn"
        when "tajikistan" then   "tjk"
        when "tj" then   "tjk"
        when "tjk" then   "tjk"
        when "tanzania united republic of" then   "tza"
        when "tz" then   "tza"
        when "tza" then   "tza"
        when "tanzania" then   "tza"
        when "tanzania united rep of" then   "tza"
        when "tanzania then   united rep. of" then   "tza"
        when "thailand" then   "tha"
        when "th" then   "tha"
        when "tha" then   "tha"
        when "timor-leste" then   "tls"
        when "tl" then   "tls"
        when "tls" then   "tls"
        when "east timor" then   "tls"
        when "togo" then   "tgo"
        when "tg" then   "tgo"
        when "tgo" then   "tgo"
        when "tokelau" then   "tkl"
        when "tk" then   "tkl"
        when "tkl" then   "tkl"
        when "tonga" then   "ton"
        when "to" then   "ton"
        when "ton" then   "ton"
        when "trinidad and tobago" then   "tto"
        when "tt" then   "tto"
        when "tto" then   "tto"
        when "trinidad  tobago" then   "tto"
        when "trinidad & tobago" then   "tto"
        when "tunisia" then   "tun"
        when "tn" then   "tun"
        when "tun" then   "tun"
        when "turkey" then   "tur"
        when "tr" then   "tur"
        when "tur" then   "tur"
        when "turkmenistan" then   "tkm"
        when "tm" then   "tkm"
        when "tkm" then   "tkm"
        when "turks and caicos islands" then   "tca"
        when "tc" then   "tca"
        when "tca" then   "tca"
        when "turks  caicos islands" then   "tca"
        when "turks and caicos" then   "tca"
        when "turks and caicos isl" then   "tca"
        when "turks & caicos islands" then   "tca"
        when "turks and caicos isl." then   "tca"
        when "tuvalu" then   "tuv"
        when "tv" then   "tuv"
        when "tuv" then   "tuv"
        when "uganda" then   "uga"
        when "ug" then   "uga"
        when "uga" then   "uga"
        when "ukraine" then   "ukr"
        when "ua" then   "ukr"
        when "ukr" then   "ukr"
        when "united arab emirates" then   "are"
        when "ae" then   "are"
        when "are" then   "are"
        when "uae" then   "are"
        when "united kingdom" then   "gbr"
        when "gb" then   "gbr"
        when "gbr" then   "gbr"
        when "united states" then   "usa"
        when "us" then   "usa"
        when "usa" then   "usa"
        when "u.s.a." then   "usa"
        when "united states of america" then   "usa"
        when "united states minor outlying islands" then   "umi"
        when "um" then   "umi"
        when "umi" then   "umi"
        when "uruguay" then   "ury"
        when "uy" then   "ury"
        when "ury" then   "ury"
        when "uzbekistan" then   "uzb"
        when "uz" then   "uzb"
        when "uzb" then   "uzb"
        when "uzbekistan sum" then   "uzb"
        when "vanuatu" then   "vut"
        when "vu" then   "vut"
        when "vut" then   "vut"
        when "venezuela bolivarian republic of" then   "ven"
        when "ve" then   "ven"
        when "ven" then   "ven"
        when "venezuela" then   "ven"
        when "viet nam" then   "vnm"
        when "vn" then   "vnm"
        when "vnm" then   "vnm"
        when "vietnam" then   "vnm"
        when "virgin islands british" then   "vgb"
        when "vg" then   "vgb"
        when "vgb" then   "vgb"
        when "british virgin islands" then   "vgb"
        when "virgin islands (british)" then   "vgb"
        when "u.k. virgin islands" then   "vgb"
        when "virgin islands u.s." then   "vir"
        when "vi" then   "vir"
        when "vir" then   "vir"
        when "u.s. virgin islands" then   "vir"
        when "us virgin islands" then   "vir"
        when "virgin islands us" then   "vir"
        when "virgin islands (us)" then   "vir"
        when "virgin islands (u.s.)" then   "vir"
        when "virgin islands then   u.s." then   "vir"
        when "wallis and futuna" then   "wlf"
        when "wf" then   "wlf"
        when "wlf" then   "wlf"
        when "western sahara" then   "esh"
        when "eh" then   "esh"
        when "esh" then   "esh"
        when "yemen" then   "yem"
        when "ye" then   "yem"
        when "yem" then   "yem"
        when "yemen republic of" then   "yem"
        when "zambia" then   "zmb"
        when "zm" then   "zmb"
        when "zmb" then   "zmb"
        when "zimbabwe" then   "zwe"
        when "zw" then   "zwe"
        when "zwe" then   "zwe"
        ELSE country END as country 