$report = @{
    'frequency' = 'Monday';
    'subject' = 'Intent Media SCA Weekly Snapshot for #{$entity} - $formatted_date';
    'default_workbook' = 'External SCA Advertiser Report for Advertisers';
    'assets' = @(
        @{
            'worksheet' = 'Topline';
            'filetype' = 'png';
            'attached' = $false;
            'embedded' = $true;
            'filename' = '#{$entity}-#{$loop_through_parameter}';
            'parameters' = @{
                'Advertiser' = '#{$entity}';
                'Product Category' = '#{$loop_through_parameter}'
            }
        },
        @{
            'worksheet' = 'CSV Download';
            'filetype' = 'csv';
            'attached' = $true;
            'embedded' = $false;
            'filename' = '#{$yesterday}-Intent-Media-#{$entity}-Data';
            'parameters' = @{
                'Advertiser' = '#{$entity}';
                'Product Category' = '#{$loop_through_parameter}'
            };
            'column_order' = @("Advertiser","Date","Local Currency","Product Category Type","Clicks","Impressions","Spend","Average Position","Spend in Local Currency","CPC in Local Currency","CPC","CTR")
        }
    );
    'entities' = @{
        'Air Canada' = @('Flights');
        'Airfarewatchdog' = @('Flights');
        'Alaska Airlines' = @('Flights');
        'ASAP Tickets' = @('Flights');
        'Aston Hotels' = @('Hotels');
        'Booking.com-ads' = @('Hotels');
        'Booking.com - US - Meta' = @('PPA');
        'Booking.com - UK' = @('Hotels');
        'Booking.com - UK - Meta' = @('PPA');
        'bookit.com' = @('Flights','Hotels');
        'BudgetAir - UK' = @('Flights');
        'BudgetPlaces - UK' = @('Hotels');
        'BusBud - Ads' = @('Flights');
        'Cathay Pacific' = @('Flights');
        'CheapFareGuru' = @('Flights');
        'CheapOair' = @('Flights');
        'CheapOair- UK ads' = @('Flights');
        'CheapOair-Canada' = @('Flights');
        'CheapTickets-Ads' = @('Flights');
        'Crowne Plaza' = @('Hotels');
        'Delta' = @('Flights');
        'ebookers - UK' = @('Hotels');
        'ebookers - UK - Meta' = @('PPA');
        'eDreams - UK' = @('Flights');
        'Easytobook - UK - Meta' = @('PPA');
        'EasyVoyage - UK' = @('Flights');
        'Etihad Airways' = @('Flights');
        'Expedia-Ads' = @('Hotels');
        'Expedia - US - Meta' = @('PPA');
        'Expedia - UK - Meta' = @('PPA');
        'Expedia - UK' = @('Flights','Hotels');
        'Faregeek - US' = @('Flights');
        'FlightHub' = @('Flights');
        'FlightNetwork' = @('Flights');
        'Fly.com' = @('Flights');
        'FlyFar' = @('Flights');
        'goSeek' = @('Hotels');
        'Getaroom - UK - Meta' = @('PPA'); 
        'Getaroom - US - Meta' = @('PPA');
        'Globehunters - UK' = @('Flights');
        'Hawaiian Airlines' = @('Flights');
        'Hilton Hotels' = @('Hotels');
        'Hipmunk-Ads' = @('Flights');
        'Holiday Inn' = @('Hotels');
        'Holiday Inn Express' = @('Hotels');
        'Hotels.com-Ads - UK' = @('Hotels');
        'Hotels.com-Ads' = @('Hotels');
        'Hotels.com - US - Meta' = @('PPA');
        'Hotels.com - UK - Meta' = @('PPA');
        'HotelsCombined - UK' = @('Hotels');
        'HotelsCombined - US' = @('Hotels');
        'Hotwire-Ads' = @('Flights','Hotels');
        'Hotwire-Meta' = @('PPA');
        'Indian Eagle' = @('Flights');
        'InsanelyCheapFlights' = @('Flights');
        'itravel2000' = @('Flights','Hotels');
        'JetaPort' = @('Hotels');
        'Jetcost - UK' = @('Flights');
        'Justairticket-ads' = @('Flights');
        'JustFly' = @('Flights');
        'Kayak Software Corporation - Ads' = @('Flights','Hotels');
        'Kugunda' = @('Hotels');
        'Kugunda - UK' = @('Hotels');
        'LAN Airlines' = @('Flights');
        'LAN - Ariadna' = @('Flights');
        'lastminute.com - UK' = @('Hotels');
        'Laterooms.com - UK' = @('Hotels');
        'Momondo' = @('Flights');
        'On the Beach - UK' = @('Hotels');
        'One Travel' = @('Flights');
        'OneTime - ads' = @('Hotels');
        'Orbitz-ads-on-Network' = @('Flights','Hotels');
        'Orbitz - US - Meta' = @('PPA');
        'OWW-ads-on-CTIX' = @('Flights');
        'Qatar Airways - ads' = @('Flights');
        'Roomer Travel - ads' = @('Hotels');
        'Skyscanner - UK' = @('Flights');
        'Skyscanner - US' = @('Flights');
        'South African Airlines' = @('Flights');
        'StudentUniverse' = @('Flights');
        'STA Travel-Ads' = @('Flights');
        'TAM airlines - Ariadna' = @('Flights');
        'Top10 - UK' = @('Hotels');
        'Travelocity-Ads' = @('Flights','Hotels');
        'Travelocity - US - Meta' = @('PPA');
        'TravelSupermarket - UK' = @('Flights', 'Hotels');
        'TripAdvisor - UK' = @('Flights','Hotels');
        'TripAdvisor' = @('Flights','Hotels');
        'Tripping.com' = @('Hotels');
        'Trivago' = @('Hotels');
        'Trivago - UK' = @('Hotels');
        'United Airlines' = @('Flights');
        'Vegas.com-ads' = @('Hotels');
        'Virgin Atlantic' = @('Flights');
        'Virgin Holidays - UK' = @('Hotels');
        'Webjet.ca' = @('Flights');
        'Webjet' = @('Flights');
        'XL Airways' = @('Flights')
    }
}
